### ISSUE TITLE
Missing Work: 1971 Aahrus notes "Closed categories and biclosed bicategories"

### ISSUE THREAD

**Issue by topological-modular-forms** [mattearnshaw/lawvere#1]
> Ross Street, _Enriched categories and cohomology with author commentary_. Originally published as: Enriched categories and cohomology, Quaestiones Mathematicae, 6 (1983), 265-283, used by permission. 2000 MSC: 18D20, 18D30. Republished in: Reprints in Theory and Applications of Categories, No. 14 (2005), pp 1-18

cites

> [12] F. W. Lawvere (1971). Closed categories and biclosed bicategories. Mathematics Institute Aarhus Universitet, Aarhus. handwritten lecture notes

as another work of Lawvere. Although I haven't been able to find a copy, I have asked about one on [MathOverflow](https://mathoverflow.net/questions/462445).

**Comment by mattearnshaw** [comment]
Thanks, I have added a placeholder entry. Of course, if you do obtain a copy please let me know.

**Comment by topological-modular-forms** [comment]
Thank _you_, I truly appreciate this project :)

I'll let you know if I'm able to find a copy. By the way, there's also a discussion going on in the category theory mailing list about a set of 1974 lecture notes of Lawvere in Laval, which I think aren't listed here. I'll let you know if someone there replies with a copy of those too.
